version: "2"
linters:
  default: all
  disable:
    # TEMPORARY DISABLE
    - cyclop
    - err113
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gocognit
    - gocritic
    - godox
    - lll
    - mnd
    - nilnil
    - noinlineerr
    - nolintlint
    - paralleltest
    - revive
    - tagliatelle
    - testifylint
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    # END TEMPORARY DISABLE
    - wsl
  enable:
    - wsl_v5

  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - github.com/dukex/operion/pkg/protocol
    exhaustruct:
      include:
        - '.+\.Test'
      exclude:
        - '.+/cli\.Command$'
    funlen:
      lines: 120
    ireturn:
      allow:
        - empty
        - error
        - stdlib
        - anon
        - generic
        - ^github.com/dukex/operion
    tagliatelle:
      case:
        rules:
          json: snake
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
